// <auto-generated />
using System;
using BonsaiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonsaiAPI.Migrations
{
    [DbContext(typeof(BonsaiContext))]
    partial class BonsaiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BonsaiAPI.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Known for stunning autumn colour. Delicate leaves and elegant branching structure. Ideal for outdoor bonsai.",
                            DifficultyLevel = "Intermediate",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Acer_palmatum_001.jpg/320px-Acer_palmatum_001.jpg",
                            Name = "Japanese Maple",
                            OriginCountry = "Japan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "One of the most forgiving bonsai species. Small leaves, graceful form and reliable growth. Great for beginners.",
                            DifficultyLevel = "Beginner",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Ulmus_parvifolia_bonsai_2.jpg/320px-Ulmus_parvifolia_bonsai_2.jpg",
                            Name = "Chinese Elm",
                            OriginCountry = "China"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic bonsai choice with needle-like foliage and dramatic deadwood possibilities. Requires outdoor placement.",
                            DifficultyLevel = "Beginner",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Juniperus_chinensis_bonsai_1.jpg/320px-Juniperus_chinensis_bonsai_1.jpg",
                            Name = "Juniper",
                            OriginCountry = "Japan"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hardy indoor bonsai with glossy leaves and strong aerial roots. Very tolerant of low-light environments.",
                            DifficultyLevel = "Beginner",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Ficus_microcarpa_bonsai_1.jpg/320px-Ficus_microcarpa_bonsai_1.jpg",
                            Name = "Ficus",
                            OriginCountry = "Southeast Asia"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Spectacular flowering bonsai producing vivid blooms in spring. Requires acidic soil and careful pruning after flowering.",
                            DifficultyLevel = "Expert",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Rhododendron_bonsai_1.jpg/320px-Rhododendron_bonsai_1.jpg",
                            Name = "Azalea",
                            OriginCountry = "Japan"
                        });
                });

            modelBuilder.Entity("BonsaiAPI.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastWateredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Trees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Height = 45.5m,
                            LastWateredDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nickname = "Old Man",
                            Notes = "Repotted in spring. Needs more sunlight.",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 8,
                            Height = 22.0m,
                            LastWateredDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nickname = "Little Cloud",
                            Notes = "Growing well. No issues.",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 15,
                            Height = 38.0m,
                            LastWateredDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nickname = "Storm",
                            Notes = "Wind-swept style. Some deadwood work done in March.",
                            SpeciesId = 3
                        });
                });

            modelBuilder.Entity("BonsaiAPI.Models.Tree", b =>
                {
                    b.HasOne("BonsaiAPI.Models.Species", "Species")
                        .WithMany("Trees")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("BonsaiAPI.Models.Species", b =>
                {
                    b.Navigation("Trees");
                });
#pragma warning restore 612, 618
        }
    }
}